name: build

on:
  push:
    branches:
      - main
      - devel

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        repository: IndeedItzGab/newb-x-supplementary-Private 
        token: ${{ secrets.PUBLIC_WORKFLOW_REPO }}


    - name: Cache env files
      uses: actions/cache@v3
      with:
        key: env-files
        path: |
          ${{ github.workspace }}/env
          ${{ github.workspace }}/data

    - name: Setup build env
      run: .\setup.bat

    - name: Build Merged pack
      run: ./final.sh -w -p merged
      shell: bash

    - name: Upload NewbXSupplementary Zip
      uses: actions/upload-artifact@v3
      with:
        name: NewbXSupplementary
        path: ./build/merged


