name: build

on:
  push:
    branches:
      - main
      - devel
    paths:
      - '**/*'
      - '!./build/merged/temp'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        repository: IndeedItzGab/newb-x-supplementary-Private 
        token: ${{ secrets.PUBLIC_WORKFLOW_REPO }}

    - name: Cache env files
      uses: actions/cache@v4
      with:
        key: env-files
        path: |
          ${{ github.workspace }}/env
          ${{ github.workspace }}/data

    - name: Setup build env
      run: .\setup.bat
      
    - name: Building Merged pack
      run: ./final.sh -w -p merged
      shell: bash
      
    - name: Zip Merged pack
      run: Compress-Archive -Path ./build/merged/temp/* -DestinationPath ./build/merged/NewbXSupplementary.mcpack
      
    - name: Deleting Temp folder
      run: Remove-Item -Path ./build/merged/temp -Force -Recurse

    - name: Upload Newb-X-Supplementary Zip
      uses: actions/upload-artifact@v4
      with:
        name: NewbXSupplementary
        path: ./build/merged
      


